---
apiVersion: v1
kind: Service
metadata:
  name: service-demo
  labels: 
    app: service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
  type: ClusterIP