---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-example
  labels:
    app: rc
spec:
  replicas: 3
  selector:
    app: rc
  template:
    metadata:
      labels:
        app: rc
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        ports:
        - name: webport
          containerPort: 80
