---
apiVersion: v1
kind: Pod
metadata:
  name: registry-demo
spec:
  containers:
    - name: nginx
      image: registry.cn-shanghai.aliyuncs.com/lxli/nginx:v1.0
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: registry-secret