---
apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-demo
spec:
  restartPolicy: Never
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Never
      command: ['/bin/sh', '-c', 'env']
      ports:
        - containerPort: 80
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: cm-demo2
              key: db.host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: cm-demo2
              key: db.port